stages:
  train_test_split:
    cmd: python src/train_test_split.py
    deps:
    - data/GOLD_XYZ_OSC.0001_1024.hdf5
    - src/datasets
    - src/train_test_split.py
    - src/config.py
    outs:
    - data/test_indices.csv
    - data/train_indices.csv
  sample_data:
    cmd: python src/sample_data.py
    deps: 
    - data/GOLD_XYZ_OSC.0001_1024.hdf5
    - data/train_indices.csv
    - src/datasets
    - src/config.py
    - src/sample_data.py
    outs:
    - data/data.pkl
  diagrams:
    cmd: python src/diagrams.py
    params:
    - diagrams
    deps:
    - data/data.pkl
    - src/diagrams.py
    - src/config.py
    - src/modurec/features
    - src/utils.py
    outs:
    - data/diagrams.pkl
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/data.pkl
    - data/diagrams.pkl
    - src/featurize.py
    - src/config.py
    - src/modurec/features
    - src/feature_list.py
    - src/utils.py
    outs:
    - data/features.pkl


