stages:
  train_test_split:
    cmd: python src/train_test_split.py
    deps:
    - data/GOLD_XYZ_OSC.0001_1024.hdf5
    - src/datasets
    - src/train_test_split.py
    - src/config.py
    outs:
    - data/test_indices.csv
    - data/train_indices.csv
  sample_data:
    cmd: python src/sample_data.py
    deps: 
    - data/GOLD_XYZ_OSC.0001_1024.hdf5
    - data/train_indices.csv
    - src/datasets
    - src/config.py
    - src/sample_data.py
    outs:
    - data/data.pkl
